version: '3'
services:
  redis-core:
    image: thomaslamendola/redis-core:latest
    container_name: "redis-core"
    depends_on:
      - redis
    networks:
      - "network1"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
    networks:
      - "network1"

volumes:
   redisdata:

networks:
   network1: